### ISSUE TITLE
BrightCove Doesn't Show Subtitle with iOS (Swift)

### ISSUE THREAD

**Issue by blackknight101** [brightcove/brightcove-player-sdk-ios-sidecarsubtitles#3]
Hey guy,

I just playing a video from Brightcove and try to add subtitle

This is my code. But the video doesn't show subtitle. Help me, please.

func registerBrightCove(clsVideo:Cls_VideoDetail,viewController:UIViewController) {
        let manager = BCOVPlayerSDKManager.shared()!

        playbackController = manager.createSidecarSubtitlesPlaybackController(viewStrategy: nil)

        playbackController?.analytics.account = clsVideo.accountId

        playbackController?.delegate = self

        playbackController?.isAutoAdvance = true

        playbackController?.isAutoPlay = true

        let options = BCOVPUIPlayerViewOptions()

        options.presentingViewController = viewController

        let controlsView = BCOVPUIBasicControlView.withVODLayout()

        playerView = BCOVPUIPlayerView.init(playbackController: playbackController, options: options, controlsView: controlsView)!

        playerView?.controlsView.layout = nil

        playerView?.delegate = self

        playerView?.frame = videoContainer.bounds

        playerView?.autoresizingMask = [.flexibleHeight, .flexibleWidth]

        videoContainer.addSubview(playerView!)

        requestContentFromPlaybackService(clsVideo: clsVideo)
    }

func requestContentFromPlaybackService(clsVideo:Cls_VideoDetail) {

        let playbackService = BCOVPlaybackService(accountId: clsVideo.accountId, policyKey: clsVideo.policyKey)!

        playbackService.findVideo(withVideoID: clsVideo.videoId, parameters: nil) {

            (video: BCOVVideo?, dict: [AnyHashable:Any]?, error: Error?) in

            if let v = video {

                self.currentVideo = v

                self.playbackController?.setVideos([v] as NSFastEnumeration!)
            }
        }
    }

func addSubTitle(_ subTitles: [[String: Any]]) {

        self.currentVideo = self.currentVideo?.update({ (mutableVideo) in

            var updatedDictionary = mutableVideo?.properties

            updatedDictionary?[kBCOVSSVideoPropertiesKeyTextTracks] = subTitles

            mutableVideo?.properties = updatedDictionary
        })

        self.playbackController?.setVideos([self.currentVideo] as NSFastEnumeration)
    }

    

    func removeSubTitle() {

        self.currentVideo = self.currentVideo?.update({ (mutableVideo) in

            var updatedDictionary = mutableVideo?.properties

            // Store text tracks in the text tracks property

            updatedDictionary?[kBCOVSSVideoPropertiesKeyTextTracks] = []

            mutableVideo?.properties = updatedDictionary
        })
        self.playbackController?.setVideos([self.currentVideo] as NSFastEnumeration)
    }

Thank you so much

**Comment by Hesham-Salama** [comment]
Why didn't you provide your solution?
