### ISSUE TITLE
How to manual open the closed caption selection view controller?

### ISSUE THREAD

**Issue by hxdev** [brightcove/brightcove-player-sdk-ios-sidecarsubtitles#4]
Hello,

Currently, I do customize the player control. I face the problem that I cannot open the closed caption selection view controller as the native caption button do. I read all the README but still cannot figure out how to do it. Thanks in advance.

**Comment by sjbushell** [comment]
The sample app "PlayThree" from our PLAY 2016 repo shows some player customizations. I just ran them, and the selection button works normally. Please have a look: https://github.com/BrightcoveOS/PLAY2016_iOS

Also, you may want to visit the support forum in the future: https://groups.google.com/forum/#!forum/brightcove-native-player-sdks
