### ISSUE TITLE
Cannot combine with IMA

### ISSUE THREAD

**Issue by alex-taffe** [brightcove/brightcove-player-sdk-ios-sidecarsubtitles#6]
When attempting to integrate IMA and subtitles together with the following pod spec:
```
  pod 'Brightcove-Player-IMA'
  pod 'Brightcove-Player-SDK-SidecarSubtitles'
```
I get this error:
```
[!] The 'Pods-SportsTablet' target has frameworks with conflicting names: brightcoveplayersdk.framework.
```
I have a suspicion that it's because the IMA is coming from the private pod spec repo and sidecar is coming from public and thus they have different core SDK versions, but I'm not sure.

**Comment by timothyrodgers** [comment]
From https://github.com/brightcove/brightcove-player-sdk-ios-sidecarsubtitles:
> This version of the Sidecar Subtitles plugin is no longer supported. The Sidecar Subtitles plugin has been repackaged with the Core SDK. Refer to the latest release of the [Brightcove Player SDK for iOS](https://github.com/brightcove/brightcove-player-sdk-ios).

Try removing `Brightcove-Player-SDK-SidecarSubtitles` from your Podfile.

**Comment by alex-taffe** [comment]
Ahh got it, thanks!

**Comment by alex-taffe** [comment]
@timothyrodgers do you know of a way to add captions to the  IMA playback controller? We're using `createIMAPlaybackControllerWithSettings` right now but it seems we need to use `createSidecarSubtitlesPlaybackController` for captioning
